# Generated by Django 5.0.3 on 2024-04-29 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_enrollment_status_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password_last_Change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('inProgress', 'inProgress'), ('finiched', 'finiched'), ('isntStart', 'isntStart')], default='isntStart', max_length=20),
        ),
    ]
