# Generated by Django 5.0.3 on 2024-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_password_last_change_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('isntStart', 'isntStart'), ('finiched', 'finiched'), ('inProgress', 'inProgress')], default='isntStart', max_length=20),
        ),
    ]
