# Generated by Django 5.0.3 on 2024-04-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpage',
            name='Emploit',
            field=models.ImageField(default='images/09.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='teacherpage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('isntStart', 'isntStart'), ('inProgress', 'inProgress'), ('finiched', 'finiched')], default='isntStart', max_length=20),
        ),
        migrations.DeleteModel(
            name='Emploit',
        ),
    ]
