# Generated by Django 5.0.3 on 2024-04-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teacherpage_emploit_teacherpage_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('inProgress', 'inProgress'), ('isntStart', 'isntStart'), ('finiched', 'finiched')], default='isntStart', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherpage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
