# Generated by Django 5.0.3 on 2024-04-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_enrollment_status_alter_teacherpage_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpage',
            name='title',
            field=models.CharField(default='استاذ', max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('finiched', 'finiched'), ('isntStart', 'isntStart'), ('inProgress', 'inProgress')], default='isntStart', max_length=20),
        ),
    ]
