# Generated by Django 5.0.3 on 2024-05-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_teacherpage_title_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(default='others', max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('finiched', 'finiched'), ('inProgress', 'inProgress'), ('isntStart', 'isntStart')], default='isntStart', max_length=20),
        ),
    ]
