# Generated by Django 5.0.4 on 2024-05-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='zoom_link',
            field=models.URLField(default='', max_length=100, null=True),
        ),
    ]
